version: 2
jobs:
  build:
    working_directory: /root/project/
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Setup testing environment
          command: |
            pip install '.[tests]'
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
workflows:
  version: 2
  workflow:
    jobs:
      - build
